### ISSUE TITLE
quarkus-ecosystem-ci is cannot on Splunk extension 

### ISSUE THREAD

**Issue by vietk** [quarkusio/quarkus-ecosystem-ci#52]
Hello, 

I noticed that quarkus-ecosystem-ci job of the splunk extension is failing with :

![image](https://user-images.githubusercontent.com/1568850/114893872-6a97dc00-9e0e-11eb-9dea-a87bd297c00f.png)

On one side it's due a wrong branch configuration in the workflow of the extension
```
      - name: Checkout Ecosystem
        uses: actions/checkout@v2
        with:
          repository: ${{ env.ECOSYSTEM_CI_REPO }}
          ref: main
          path: ecosystem-ci
```
It's referencing the `main` branch.

But the thing is that quarkus-ecosystem-ci haven't moved to default `main` branch naming, yet.

I could update the extension but I think it's good also that the branch is renamed, for other extension that uses `master` default branch will still be working[ after that ](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#about-renaming-branches)
